
[mgr]
  prepend_keymap = [
    { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
		{ on = "C", run = "plugin ouch", desc = "Compress with ouch" },
		{ on = "y", run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ] },
		# { on = "C-A-p", run = "yank" },
  ]

